# example netlify.toml
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=3000;
    includeSubDomains;
    preload'''